### ISSUE TITLE
Sidebar form persists when navigating page

### ISSUE THREAD

**Issue by scottgallant** [tinacms/tina-cloud-starter#104]
When navigating to /about, and opening the sidebar, I see the "Welcome to Tina, let's set up a form" copy in the sidebar. 

Then if I navigate to /home, I still see that same empty state copy in the sidebar. 

See gif:

![PDwWKWicWl](https://user-images.githubusercontent.com/776019/127046033-60cfeb99-9fc4-415e-859b-e7e00b940b0a.gif)

**Comment by mitchmac** [comment]
@scottgallant If you happen to run into this one again, can you check your dev console for errors & network activity for failed requests? I believe that's the default form state while waiting for the API response

**Comment by scottgallant** [comment]
Duplicate issue. Closing.
