### ISSUE TITLE
Can't create paragraph easily in About page

### ISSUE THREAD

**Issue by DirtyF** [tinacms/tina-cloud-starter#108]
Editing content on the About page is harder than it should at the moment.
Can we set the page so that you can type in the textarea and hit return here?

Demo: https://www.loom.com/share/589745ee28a24bd7818d1a4b281a33a3

Env: Firefox/macOS

**Comment by mitchmac** [comment]
This issue should be fixed (needs testing)

**Comment by logan-anderson** [comment]
Tested and seems to be working for me!

**Comment by mitchmac** [comment]
Looks good!
