### ISSUE TITLE
New blocks don't show up until save & page refresh

### ISSUE THREAD

**Issue by jamespohalloran** [tinacms/tina-cloud-starter#11]
<img width="665" alt="Screen Shot 2021-01-22 at 11 05 50 AM" src="https://user-images.githubusercontent.com/3323181/105507655-d9e3b100-5ca1-11eb-8053-7dd0c5976d93.png">
Here I added a few new blocks, the main page doesn't seem to update its content until I save and refresh.
The same goes for deleting blocks

**Comment by jamespohalloran** [comment]
https://github.com/tinacms/tinacms/issues/1669
This should fix this issue

**Comment by jeffsee55** [comment]
This would be closed by https://github.com/tinacms/tina-graphql-gateway/pull/127
