### ISSUE TITLE
Default form (getGlobalDocument) is confusing when editing content

### ISSUE THREAD

**Issue by mitchmac** [tinacms/tina-cloud-starter#110]
Opening the sidebar to edit on a page (like /about) opens the getGlobalDocument form. It's not immediately obvious what this form is for.

There are a few changes that might help:

1. Default to the getPagesDocument form, as content edits are more frequent than global edits
2. Label each form with a user friendly name
3. Provide help context within each form about their purpose

![Screen Shot 2021-07-27 at 11 24 19 AM](https://user-images.githubusercontent.com/618212/127173628-37561042-e1c5-4dbb-975d-b509594fe68d.png)

**Comment by jeffsee55** [comment]
TODO: check that `formifyCallback` is firing

**Comment by jeffsee55** [comment]
I think we need a better API for this https://github.com/tinacms/tina-cloud-starter/pull/128

**Comment by scottgallant** [comment]
If this can't be solved quickly, Is there a work-around that we can use just for the starter site? Perhaps we could move header/footer/theme editing to global plugins and just leave getPagesDocument? 

Tagging @spbyrne

**Comment by jeffsee55** [comment]
@scottgallant - @dwalkr implemented a simpler API for this [here](https://github.com/tinacms/tinacms/issues/1956). That's merged so we can add it tomorrow.

**Comment by DirtyF** [comment]
Should be fixed by https://github.com/tinacms/tinacms/pull/1985/files I guess?
