### ISSUE TITLE
Improve default Lighthouse Score

### ISSUE THREAD

**Issue by DirtyF** [tinacms/tina-cloud-starter#115]
Previously we had a perfect Lighthouse Score, would be nice if we could get all green on this one too.
https://developers.google.com/speed/pagespeed/insights/?url=https%3A%2F%2Ftina-cloud-starter-orcin.vercel.app%2F

**Comment by spbyrne** [comment]
I'll see about getting these back to where they were but I wouldn't prioritize it over other features. For instance, adding an image field will give you an image of unpredictable width/height, so setting a fixed image width/height isn't possible and so will always be flagged by lighthouse. Lighthouse isn't a perfect reflection of the user's experience so shooting for good scores is fine but perfect isn't necessary.

**Comment by DirtyF** [comment]
Oh, I thought using Next/image component would solve the issue: https://developers.google.com/speed/pagespeed/insights/?url=https%3A%2F%2Fimage-component.nextjs.gallery%2Flayout-responsive

**Comment by spbyrne** [comment]
I moved the default hero image to Cloudinary and that gave an extra couple points. Getting 94/100, so very good. At this point the page is almost 400kb of JS, which is 80% of the transfer size; any big gains will be reducing JS, not through images/css at this point.

**Comment by spbyrne** [comment]
I'm getting 100% on desktop despite the width/height warning so I suspect it's not a hard requirement and if we reduce the JS bundle size we'll hit 100 across the board.

**Comment by spbyrne** [comment]
<img width="906" alt="Screen Shot 2022-03-17 at 2 43 40 PM" src="https://user-images.githubusercontent.com/5075484/158863094-c13a3612-e24d-4731-a9c2-b42a0de96a1c.png">
<img width="857" alt="Screen Shot 2022-03-17 at 2 43 52 PM" src="https://user-images.githubusercontent.com/5075484/158863135-33ee66b3-c317-482c-876e-cd92dfc94d39.png">

Closing; I'm okay with these numbers.
