### ISSUE TITLE
Strange nav behaviours in edit mode

### ISSUE THREAD

**Issue by logan-anderson** [tinacms/tina-cloud-starter#123]
See: https://discord.com/channels/835168149439643678/848932514911354880/870269806992035851

CC @damiensedgwick

**Comment by DirtyF** [comment]
Same for me https://www.loom.com/share/5f1e2e91c34e4774a02d6e4fe5728446

**Comment by damiensedgwick** [comment]
Love looms!

I can confirm this is my experience with the navigation when connected to Tina Cloud.

**Comment by logan-anderson** [comment]
@spbyrne Did most of the coding of the new starter so he might know the issue. If not I can take a look at next week.

**Comment by logan-anderson** [comment]
I merged a PR that fixed the issue when not in edit mode.

**Comment by damiensedgwick** [comment]
Nice work!
