### ISSUE TITLE
Demo: Edit with Tina makes the site unresponsive

### ISSUE THREAD

**Issue by DirtyF** [tinacms/tina-cloud-starter#135]
```gherkin
Given you're visiting our default demo URL https://tina-cloud-starter-orcin.vercel.app/
When you click on the Edit with Tina button
Then you get a blank page because you can't connect through Tina Cloud
```

test: https://www.loom.com/share/e4b2655187ee46ca882a38bbd39b63e0

**Comment by jamespohalloran** [comment]
I ran into this too. The console loops a:
```
Error: The following props are required when using the Tina Cloud Client, please make sure they are being passed to TinaCloudAuthWall:
     clientId
```
In my case, I didn't have `NEXT_PUBLIC_TINA_CLIENT_ID ` set as an environment variable, but we should ideally show an error to the user in this case.

**Comment by DirtyF** [comment]
For our demo, it would be good to trigger a specific event that would inform people that this site is in read-only mode and invite you in order to test editing capabilities to fork the starter on Tina Cloud.

**Comment by DirtyF** [comment]
For the demo we should hide the edit button with an env var set on Vercel like EDIT_BUTTON=0

**Comment by DirtyF** [comment]
https://tina-cloud-starter-orcin.vercel.app/ doesn't show the edit button anymore.
