### ISSUE TITLE
Content on Home and About pages isn't loading   

### ISSUE THREAD

**Issue by scottgallant** [tinacms/tina-cloud-starter#140]
After navigating between the **home** and **about** pages, I need to hard refresh in order to see the proper content on the page and in Tina. 

See video: [https://www.loom.com/share/561b1e2621464fff97e744bd23130848](https://www.loom.com/share/561b1e2621464fff97e744bd23130848)

**Comment by scottgallant** [comment]
This is a duplicate issue (see [here](https://github.com/tinacms/tina-cloud-starter/issues/123)), but I'll leave this open incase my loom provides any additional insights that might be needed.

**Comment by mitchmac** [comment]
Closing this so we're not confused by the duplicate issue and [related PR](https://github.com/tinacms/tina-cloud-starter/pull/136)
