### ISSUE TITLE
Nav item indexing issues

### ISSUE THREAD

**Issue by jamespohalloran** [tinacms/tina-cloud-starter#143]
Noticed a few weird issues with the list / nav items

https://www.loom.com/share/c0908295966e4c7fa6de76c783692cbe

- [ ] Rearranging the nav-items isn't reflected in the page (until the nav-item itself is edited)

https://www.loom.com/share/7c9387e0483441128ab24b746776f33a
- [ ] Nav item is occasionally duplicated.

It may make sense to split this up into separate issues.

**Comment by spbyrne** [comment]
There was an upstream fix so this should be resolved but there may be a delay. I'll check once things are published.
