### ISSUE TITLE
Create document breaks

### ISSUE THREAD

**Issue by scottgallant** [tinacms/tina-cloud-starter#147]
1. When creating a new document, it says "choose template", but there are no options
<img width="806" alt="Screen Shot 2021-08-05 at 3 25 41 PM" src="https://user-images.githubusercontent.com/776019/128402588-58eb30bf-1450-44db-8ec4-871020ac280f.png">

2. It still kicks you over to a new page, but you get a 404. 
<img width="814" alt="Screen Shot 2021-08-05 at 3 26 03 PM" src="https://user-images.githubusercontent.com/776019/128402247-c8a91d9b-0f72-4d32-a09c-ddff41b883a2.png">

3. Then things fly off the handle ;) 

<img width="760" alt="Screen Shot 2021-08-05 at 3 27 54 PM" src="https://user-images.githubusercontent.com/776019/128402324-4ed1d3de-a374-4a99-a4d8-54b674ac7423.png">

4. Then the refresh button didn't work (filed new issue for that https://github.com/tinacms/tinacms/issues/2002)

**Comment by mitchmac** [comment]
@jeffsee55 - you mentioned you were thinking about something like this problem today?

**Comment by jeffsee55** [comment]
It's probably related, @scottgallant what was the URL that gave you the 404?

**Comment by scottgallant** [comment]
@jeffsee55 , after adding a new post, I get redirected to that post's url. In this case it's 

https://tina-cloud-starter-51pp00m9w-scottgallant.vercel.app/posts/test2 

that page is broken, and the /post page is broken.

**Comment by jeffsee55** [comment]
Closed by https://github.com/tinacms/tinacms/pull/2004
