### ISSUE TITLE
Delay when navigating the Tina Cloud Starter

### ISSUE THREAD

**Issue by scottgallant** [tinacms/tina-cloud-starter#149]
Navigating around the starter feels clunky. If you click a page it takes a few seconds to load. 

https://www.loom.com/share/acfa34eb297e4d2ba40ade1edf71b7a2

**Comment by mitchmac** [comment]
@scottgallant is your site running from `yarn dev` with the localclient in the video?

**Comment by scottgallant** [comment]
Running on Vercel after completing the starter flow

**Comment by mitchmac** [comment]
@scottgallant I think I see the editing pencil, so edit mode was on?

**Comment by scottgallant** [comment]
Yes

**Comment by spbyrne** [comment]
That seems quite slow. Also there's a spinner that's designed to show when loading content, and a different spinner when editing is enabled.. neither seem to be showing. I wonder what it's hanging on specifically.

**Comment by DirtyF** [comment]
I don't reproduce this behaviour, when connected I can see a loading state before the page is editable:
https://www.loom.com/share/043329a113524873adc8e9c76f4cd5d8

**Comment by mitchmac** [comment]
Maybe a dark mode issue?

**Comment by spbyrne** [comment]
I don't think so.

**Comment by DirtyF** [comment]
Just did a quick test and I can see the overlay too in dark mode.

**Comment by logan-anderson** [comment]
@scottgallant @spbyrne @mitchmac 

This issue happens in edit mode. Its because the props are being fetched from Github which is slow. We should probably go into a loading state when this happens.

**Comment by mitchmac** [comment]
Loading state should be more helpful with next release
