### ISSUE TITLE
Description and readme 

### ISSUE THREAD

**Issue by scottgallant** [tinacms/tina-cloud-starter#150]
If you follow this link you and click edit, your browser tab crashes. 

<img width="909" alt="Screen Shot 2021-08-05 at 3 56 47 PM" src="https://user-images.githubusercontent.com/776019/128406250-7dba96cb-37dd-49c1-8f0a-76763702f249.png">

Then you get this: 

<img width="1424" alt="Screen Shot 2021-08-05 at 9 53 56 AM" src="https://user-images.githubusercontent.com/776019/128406271-f19afb58-f5e5-4261-b41e-a5394b63796d.png">

Also, should we add local dev commands to the readme, to save people from having to read the guide just to test it out? (tagging  @jamespohalloran because I think you might have taken this over)

**Comment by jamespohalloran** [comment]
Opened a PR within tinacms that should improve the white screen of death issue:
https://github.com/tinacms/tinacms/pull/2003

> Also, should we add local dev commands to the readme, to save people from having to read the guide just to test it out? (tagging @jamespohalloran because I think you might have taken this over)

I'm drawing a bit of a blank on my involvement with this one :)

**Comment by scottgallant** [comment]
Oops.I meant to tag @perkinsjr

**Comment by perkinsjr** [comment]
This was one thing I did not take on @scottgallant this was @DirtyF

**Comment by DirtyF** [comment]
Duplicate of #135

**Comment by DirtyF** [comment]
https://tina-cloud-starter-orcin.vercel.app/ doesn't show the edit button by default anymore to avoid going in a weird state.

**Comment by jamespohalloran** [comment]
Also fixed this on the other side, if a user tries to manually go to the admin path, they'll see this instead of hanging the browser:
<img width="919" alt="Screen Shot 2021-08-10 at 1 29 18 PM" src="https://user-images.githubusercontent.com/3323181/128897346-bc4472bd-b2eb-48ff-9b75-7cbc77eeeb1f.png">

**Comment by scottgallant** [comment]
@DirtyF When I go to [that URL](https://tina-cloud-starter-orcin.vercel.app/), I'm just prompted to log into Tina Cloud, then I get the Error that James referred to.

Does this link provide any value? Perhaps link to the guide instead?

**Comment by jamespohalloran** [comment]
@scottgallant You're likely already in edit-mode for that site. If you try in incognito, you should load the static version of the site

**Comment by scottgallant** [comment]
Correct. Thanks!
