### ISSUE TITLE
Light/dark theme caching issue

### ISSUE THREAD

**Issue by scottgallant** [tinacms/tina-cloud-starter#162]
After switching the theme from Dark to Light in the global menu, I noticed when navigating pages the theme seems to randomly switch back to Dark mode.  See Loom:

https://www.loom.com/share/ec7afd6c13aa4d58986e002532edd152

**Comment by logan-anderson** [comment]
@scottgallant did you click "save" after changing the theme?

**Comment by scottgallant** [comment]
@logan-anderson I don't recall, but perhaps not. Still weird behaviour, either way.

**Comment by logan-anderson** [comment]
@scottgallant Right now, since we don't have a database layer in place, the user must save there documents before navigating to a new page
