### ISSUE TITLE
A way to fetch all the fields in all the blocks in a page?

### ISSUE THREAD

**Issue by afzalsayed96** [tinacms/tina-cloud-starter#178]
```
getPagesDocument(relativePath: $relativePath) {
  data {
    __typename
    blocks {
      __typename
      ... on PagesBlocksFeatures {
        color
        items {
          icon {
            name
            color
            style
          }
          title
          text
        }
      }
      ... on PagesBlocksContent {
        body
        color
      }
    }
  }
```

Is there a way to fetch all the `blocks` and their `fields` in a page  without having to manually type them in graphql query?

I know this is not how graphql works but having to manually add a `field`/`block` into the query everytime feels a lot of work.

**Possible alternatives**
1. Rest API
2. Sanity CMS like custom data query language: https://www.sanity.io/docs/groq

**Comment by mitchmac** [comment]
Interesting question @afzalsayed96 -- I'm not sure but maybe @jeffsee55 or @logan-anderson have some ideas.

**Comment by jeffsee55** [comment]
You can use the `dataJSON` field. Note that it does not resolve references though.

```graphql 
getPagesDocument(relativePath: $relativePath) {
  dataJSON
}
```

**Comment by afzalsayed96** [comment]
Oh thats perfect thanks!

**Comment by jeffsee55** [comment]
@afzalsayed96 we've admittedly not advertised that much, it's something we're a little hesitant on because it's not very conventional. Please let us know if you run into issues with it!
