### ISSUE TITLE
Admin page is confusing 

### ISSUE THREAD

**Issue by scottgallant** [tinacms/tina-cloud-starter#185]
I assume a lot of users are not making it to the editing UI since the Admin page in our starter is a little confusing. See [Loom recording](https://www.loom.com/share/40a66f0cfc974a85913691cd0d10ce59).

I hope this problem will go away when we have the Tina Admin in place since users would land on a more familiar, admin dashboard-like UI and could navigate to the page they want to edit.  But until then, we could be misleading a lot of users.

**Comment by spbyrne** [comment]
Closing now that this has changed.
