### ISSUE TITLE
Make it easy to deploy starter

### ISSUE THREAD

**Issue by jamespohalloran** [tinacms/tina-cloud-starter#2]
Ultimately, it would be great if we could make it easy to deploy this starter.

It would be great to have a deploy button at the end of this readme. 
With the [Vercel deploy button](https://vercel.com/docs/more/deploy-button) you can specify required parameters. We could add `NEXT_PUBLIC_REALM_NAME`, `NEXT_PUBLIC_TINA_CLIENT_ID`, and maybe: `NEXT_PUBLIC_REDIRECT_URI`.

I'm unsure what flow is the best here. The Vercel deploy button requires a git repository URL, which we won't know in advance if the user has already forked the repo.

Also, one thing to note is that the `NEXT_PUBLIC_REDIRECT_URI` needs to match the app's redirect_uri within the dashboard. 

If we cannot work out a good solution with the Vercel deploy button, maybe it's just a matter of adding some extra documentation to the readme.

This could be divided into:

- [x] Add readme instructions for deploying as-is
- [ ] Figure out the path for a "slick" deploying experience

**Comment by jamespohalloran** [comment]
What would be people's thoughts on adding something like this to the add-app flow?
https://whimsical.com/deploy-app-ui-5ez763CR9YnTjsZfXRy1AH

Instead of asking them for a "callback URL", we give them the option to quick-deploy with Vercel or Netlify, which will also fill in the callback URL field when they're done.

The UX may be a bit rough, but maybe @DirtyF @mitchmac or @spbyrne has some ideas to sharpen it up.

**Comment by spbyrne** [comment]
I like that, @jamespohalloran. It removes a lot of friction and helps people understand what the callback URL is since it gives more context.

**Comment by jamespohalloran** [comment]
So I hit a bit of a snag here unfortunately :
The flow with the Vercel deploy button NEEDS to clone the repo. It’s the same with the Netlify Deploy button. This is a bit difficult in our case because we have a chicken or the egg situation:
- In order to properly set up a Vercel deployment of the demo-repo, you need the TinaCloud app’s client-id.
- In order to create the app in TinaCloud, you need to connect it with the GitHub repo in your account.

As an alternative, I made a change to the whimsical above. We can’t use the Netlify & Vercel quick-start deploy button, but maybe it still makes sense to split the Callback URL into its own tab, and supply some docs around hosting.

**Comment by jamespohalloran** [comment]
I'll close this ticket for now. We've added instructions for hosting on Vercel or Netlify. 
https://github.com/tinacms/tina-cloud-starter/pull/3

I think eventually we'll want to consider adding hosting into the dashboard, but that can be a separate issue
