### ISSUE TITLE
Reduce size of admin page bundle

### ISSUE THREAD

**Issue by cjmcintyre** [tinacms/tina-cloud-starter#200]
![bundle sizing](https://user-images.githubusercontent.com/18439866/148142538-fe370420-e0d4-4802-ad0a-1efea060c681.png)

the current [admin/[[...tina]].tsx](https://github.com/tinacms/tina-cloud-starter/blob/3edd52ac10bc5b64cf33b0e33514e7274ef1a7b0/pages/admin/%5B%5B...tina%5D%5D.tsx) isn't loaded dynamically.

Considering it looks like Tina is favouring NextJs I recommend changing it to a dynamic import.

I'll add a PR soon which allowed me to achieve the following **78% decrease** to the size.

![bundle size 2](https://user-images.githubusercontent.com/18439866/148142783-3134f4bf-abcc-4868-8a6c-84235885db2b.png)
.

**Comment by mitchmac** [comment]
Hi @cjmcintyre -- just following up from the linked PR #201 -- does that answer (the import is basically a dependency for the admin) seem ok?

**Comment by cjmcintyre** [comment]
> Hi @cjmcintyre -- just following up from the linked PR #201 -- does that answer (the import is basically a dependency for the admin) seem ok?

Hi @mitchmac I believe it's appropriate based on the information provided I'll close this.
