### ISSUE TITLE
Hero Image does not render on Vercel

### ISSUE THREAD

**Issue by korompaiistvan** [tinacms/tina-cloud-starter#329]
Hi, I was looking for examples on how you handle images in posts and found that the hero images in the blog posts are not being rendered.

E.g. the `anotherPost` blog post clearly has a hero image but it is not being rendered on the deployed site
https://github.com/tinacms/tina-cloud-starter/blob/main/content/posts/anotherPost.mdx?plain=1#L3

![image](https://user-images.githubusercontent.com/36007115/188493608-3b4f86b2-dbbf-4393-91c0-051f0eb28ad8.png)

Checking the Network tab in devtools reveals this error for the relevant request
`invalid path: originals/3dc84ec5-afb8-4d5c-bc73-2cdff92539f6/tina-illustration.webp`

**Comment by kldavis4** [comment]
I see this with a site created using `tinacms init` - I resolved it by opening the media manager and clicking the Sync button. @jamespohalloran do we need some additional documentation and/or better handling of media for a new project?

**Comment by jamespohalloran** [comment]
> I see this with a site created using `tinacms init` - I resolved it by opening the media manager and clicking the Sync button.

Looks like our starter created with `create-tina-app` rather than an existing site added with `tinacms init` right?

> @jamespohalloran do we need some additional documentation and/or better handling of media for a new project?

Was the problem here that Tina was added to a non-main branch?

**Comment by RiddMa** [comment]
You need to enable media in Tina Cloud dashboard.

![image](https://github.com/tinacms/tina-cloud-starter/assets/49595662/9af2c773-fbe3-49da-8466-dcb107cdec2a)
