### ISSUE TITLE
Replace references to Realm name

### ISSUE THREAD

**Issue by mitchmac** [tinacms/tina-cloud-starter#35]
Replace references to Realm name in environment variables, matching README snippets, and code to Organization ID.

At the same time, it would be good to make the environment variable to be consistent with the existing Client ID env var by prefixing it with TINA.

NEXT_PUBLIC_REALM_NAME => NEXT_PUBLIC_TINA_ORGANIZATION_ID

**Comment by jpatters** [comment]
@mitchmac What is the state of this? What does it apply to?

**Comment by mitchmac** [comment]
@jpatters I think docs/env vars are updated but it looks like we still reference realm in the client (https://github.com/tinacms/tina-cloud-starter/blob/main/utils/index.ts#L27), be nice to get this all consistent.

**Comment by ashleyjanedoiron** [comment]
Dashboard now only uses organization id. I see in the .env.local.sample that we're still references NEXT_PUBLIC_ORGANIZATION_NAME though.
