### ISSUE TITLE
Author not shown in the sidebar

### ISSUE THREAD

**Issue by DirtyF** [tinacms/tina-cloud-starter#42]
Given I'm on the Vote for Petro post
When I open the sidebar
Then Author select is empty

![CleanShot 2021-04-20 at 17 42 14](https://user-images.githubusercontent.com/103008/115426861-343cd100-a201-11eb-97f1-87ee1b8ace9b.png)

Expected: I can change Author from Napolean to Pedro.

**Comment by jeffsee55** [comment]
This should be fixed in the latest release. @DirtyF should I close this or give it to you to close

**Comment by DirtyF** [comment]
I'll do a quick check and close.

**Comment by DirtyF** [comment]
This is fixed in latest release.
