### ISSUE TITLE
docs: document content creation

### ISSUE THREAD

**Issue by DirtyF** [tinacms/tina-cloud-starter#46]

**Comment by jeffsee55** [comment]
I wouldn't say this is a bug, it's just not clear what the user would want to do with it. Do you think it should be there for all pages regardless?

**Comment by DirtyF** [comment]
I didn't label it as a bug, it's just something that has been asked during user sessions. How can we create other pages?

**Comment by jeffsee55** [comment]
That's demonstrated in the `posts` section, we should probably mention that in the readme

- [ ] Add instructions in the readme about content creation

**Comment by jeffsee55** [comment]
This is mentioned in this PR https://github.com/tinacms/tinacms.org/pull/862
