### ISSUE TITLE
Hide Media Manager

### ISSUE THREAD

**Issue by DirtyF** [tinacms/tina-cloud-starter#47]
Prevent Media Manager to be shown in the sidebar while we don't support image fields on Tina cloud.

**Comment by logan-anderson** [comment]
This will require a change TinaCMS core as the media manager screen plugin is loaded by default as seen here: https://github.com/tinacms/tinacms/blob/7b2d3a3e3fedb8920c873372fc05bb271fbc40c9/packages/tinacms/src/tina-cms.ts#L114
