### ISSUE TITLE
🚧 Exception thrown when using Tina Starters

### ISSUE THREAD

**Issue by tkapa** [tinacms/tina-cloud-starter#523]
As per my conversation with Hugo, we are having issues with running `npx create-tina-app@latest`

*According to Hugo, this also applies to other starters.

![image](https://github.com/user-attachments/assets/13c38a1e-6e2a-4f97-8cb9-4827072b0a5b)
_**Figure: Issue running npx create-tina-app@latest**_

**Comment by JackDevAU** [comment]
Hey @tkapa 

I did a it of searching and it seems Chalk behaves weirdly on npm and yarn 😅
So for the moment we are downgrading the version of chalk. 
https://github.com/chalk/chalk/issues/527
