### ISSUE TITLE
Document/example for working with data files

### ISSUE THREAD

**Issue by mitchmac** [tinacms/tina-cloud-starter#62]
How do I update site-wide config rather than content files?

**Comment by DirtyF** [comment]
I believe we don't support editing data files for now, you can list options from a JSON file though. You can always store site-wide varialbes in front matter of a Markdown file.

**Comment by jeffsee55** [comment]
This would be added with the primitive types work https://github.com/tinacms/rfcs/pull/18

**Comment by mitchmac** [comment]
@jeffsee55 is there a super basic example we could get now that json support is in tina-graphql-gateway? Maybe making the top heading (https://github.com/tinacms/tina-cloud-starter/blob/main/components/helper-components.tsx#L176) configurable?

**Comment by jeffsee55** [comment]
@mitchmac we still don't have support for data files. Just json support for collections.
