### ISSUE TITLE
Boost Lighthouse scores and promote them in the readme

### ISSUE THREAD

**Issue by mitchmac** [tinacms/tina-cloud-starter#70]
The starter is built to show folks how they can use Tina without it getting in the way of their site. We could show folks how this plays out with the Lighthouse scores of the starter.

Longer term, it would be interesting to view the impact of changes on Lighthouse scores as a check during Pull Requests.

**Comment by DirtyF** [comment]
https://tina-cloud-starter-beta.vercel.app/ gives me a 50 on mobile, with some JavaScript blocking the main thread:

<img width="974" alt="CleanShot 2021-05-20 at 21 03 39@2x" src="https://user-images.githubusercontent.com/103008/119034712-ee655b00-b9ae-11eb-8c62-f6f85fa0ef37.png">

**Comment by Enigmatical** [comment]
Once the scores in an acceptable range (90+), add screenshots, direct links to the report, and maybe GitHub Badges(?) to the README.

**Comment by dwalkr** [comment]
https://github.com/emazzotta/lighthouse-badges

**Comment by logan-anderson** [comment]
I am more then happy to start working on this I will just need access to our Vercel team  @dwalkr or @jamespohalloran are you able to do that?

**Comment by jamespohalloran** [comment]
> I am more then happy to start working on this I will just need access to our Vercel team @dwalkr or @jamespohalloran are you able to do that?

Just invited you!

**Comment by logan-anderson** [comment]
The culprit of the low score was the whimsical diagram loaded in the  Iframe. It was loading ALOT of javascript including some analytics and help help scout stuff. The best solution was to remove the diagram and replace it with an image. Once that was done we can reach a much higher score.
![Screen Shot 2021-05-27 at 3 50 06 PM](https://user-images.githubusercontent.com/43075109/119881238-72659880-bf03-11eb-9dfa-9cd1544db252.png)

**Comment by logan-anderson** [comment]
PR is here: https://github.com/tinacms/tina-cloud-starter/pull/79

**Comment by logan-anderson** [comment]
latest lighthouse scores looking really good!
https://lighthouse-dot-webdotdevsite.appspot.com//lh/html?url=https%3A%2F%2Ftina-cloud-starter-orcin.vercel.app%2F

**Comment by logan-anderson** [comment]
Officially getting all 100's!!
https://lighthouse-dot-webdotdevsite.appspot.com//lh/html?url=https%3A%2F%2Ftina-cloud-starter-orcin.vercel.app%2F
