### ISSUE TITLE
Vercel deploy button can include required environment variables

### ISSUE THREAD

**Issue by mitchmac** [tinacms/tina-cloud-starter#71]
The link for the Vercel deploy button in the readme can contain required environment variables, see https://vercel.com/docs/more/deploy-button#required-environment-variables

This should make it a bit more clear which environment variables the starter is expecting to function properly when deployed.

**Comment by jamespohalloran** [comment]
I believe that query parm won't work if you're not passing in a repo_url (which we won't have in the readme, as the user will have already had to set up a fork)

**Comment by mitchmac** [comment]
@jamespohalloran yep, good catch!
