### ISSUE TITLE
Example for Inline-Editing with TinaCloud

### ISSUE THREAD

**Issue by Perni1984** [tinacms/tina-cloud-starter#78]
Hello,

we are trying to setup inline-editing with TinaCloud and are a bit overwhelmed by the different docs and concepts that exist in the TinaCloud/TinaCMS space. My current understanding is that we need to "switch" to an inlineForm inside the https://tina.io/docs/tina-cloud/client/#formify callback and then also use  https://tina.io/docs/tina-cloud/client/#field-customization to return inline-editing fields. Is that the correct approach?

Is there anywhere an example of how to setup TinaCloud including inline-forms?

Thanks in advance.

**Comment by Perni1984** [comment]
cc @npeham

**Comment by logan-anderson** [comment]
Hello @Perni1984  and @npeham thanks for your interest in Tina Cloud! We are excited about the future of inline editing with Tina Cloud but unfortunately right now inline editing with Tina Cloud does not work. [This article](https://tina.io/blog/evolution-of-inline-editing/) will explain more about the future of inline editing and how we are planning to switch to a ref based approach with inline editing. All our current inline editing are experimental and are likely to change when we support inline editing with Tina Cloud.

We apologize for the inconvenience.

Side Note:
You had the right idea but unfortunately the way we are generating the forms does not allow for inline editing. We are focused on sidebar editing with Tina.

**Comment by Perni1984** [comment]
@logan-anderson thanks for the info, makes perfect sense.

**Comment by DirtyF** [comment]
We didn't start an RFC for the next to come inline editing API, you can subscribe or submit one on https://github.com/tinacms/rfcs if you have ideas about how to elegantly solve the implementation and provide a single developer experience, whether it's to generate forms for sidebar editing or inline editing 😊
