### ISSUE TITLE
After logging in, I see “Please wait while we log you in” until refresh

### ISSUE THREAD

**Issue by jamespohalloran** [tinacms/tina-cloud-starter#8]
After logging in, on the admin-local & admin pages, I see the text “Please wait while we log you in”. 
After I refresh, I see the correct admin page

**Comment by DirtyF** [comment]
Is this valid, went through the starter today and didn't experience this 🤔

**Comment by jamespohalloran** [comment]
Yep I think Jeff fixed this one
