### ISSUE TITLE
Make it harder to misunderstand / misconfigure NEXT_PUBLIC_USE_LOCAL_CLIENT

### ISSUE THREAD

**Issue by jamespohalloran** [tinacms/tina-cloud-starter#89]
I've seen a few users run into issues with the `NEXT_PUBLIC_USE_LOCAL_CLIENT` environment variable. 

- Some users have not understood that locally, things are talking to the local server, instead of Tina Cloud.
- I've also seen some users try and use `NEXT_PUBLIC_USE_LOCAL_CLIENT` on their deployed site (which wouldn't work in most cases).

I'm open to other suggestions, but I was wondering if offering multiple scripts might help with the issue:

```
"scripts": {
    "dev-local": "cross-env NEXT_PUBLIC_USE_LOCAL_CLIENT=1 yarn tina-gql server:start -c \"next dev\"",
    "dev": "yarn tina-gql server:start -c \"next dev\"",
    // ...
}
```

I could see this offering a few benefits:

- I think it would be unlikely that users would try and use the local client on Vercel / Netlify
- When users enter dev-local, it gives more an indicator that things are running locally (compared to the more tucked away .env approach)
- There are only 2 environment variables to use (client-id / org-id), regardless if you are working locally, or on Vercel/Netlify. If these are eventually generated in a .tina folder with `tina init` down the road, we can avoid using environment variables altogether.

**Comment by logan-anderson** [comment]
@jamespohalloran I like this approach!

Would love to know what @jeffsee55 thinks.

**Comment by jeffsee55** [comment]
Yeah this seems like a great approach to me. If we did do this, can we remove the check for an .env when using `dev-local`?

https://github.com/tinacms/tina-cloud-starter/blob/main/utils/index.ts#L14-L19

**Comment by jamespohalloran** [comment]
> Yeah this seems like a great approach to me. If we did do this, can we remove the check for an .env when using `dev-local`?
> 
> https://github.com/tinacms/tina-cloud-starter/blob/main/utils/index.ts#L14-L19

Yeah, that makes sense to me. It makes those warnings more impactful for when they are actually needed.
