### ISSUE TITLE
Investigate/test CSP use with the starter

### ISSUE THREAD

**Issue by mitchmac** [tinacms/tina-cloud-starter#92]
[Content security policies](https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP) provide an extra layer of security for various theoretical vulnerabilities. We could provide a sample CSP implementation in the starter or use the starter to guide documentation on potential CSP approaches.

**Comment by DirtyF** [comment]
Next.js has security headers: https://nextjs.org/docs/advanced-features/security-headers

**Comment by jeffsee55** [comment]
> provide an extra layer of security for various theoretical vulnerabilities

We may run into a few snags with `unsafe-inline`. Looks like that's still an issue

https://github.com/styled-components/styled-components/issues/887#issuecomment-828627183
