### ISSUE TITLE
DX: Check port 3000 is not already in use

### ISSUE THREAD

**Issue by DirtyF** [tinacms/tina-cloud-starter#94]
## Context
With Next.js default CRA you can't run two server on the same port, if you try to launch `next` in two terminals, you get an error: `Port 3000 already in use` and the command exits.

## Issue

Given you're already running another project on port `3000`
When you do use tina cloud starter default `yarn dev` command
Then the output tells you the site is accessible on `http://localhost:3000 `
And when you click you land on the other project already running on `3000`
And you don't know if tina cloud starter runs on another port.

<img width="1279" alt="CleanShot 2021-06-29 at 16 21 29@2x" src="https://user-images.githubusercontent.com/103008/123816525-add6f680-d8f7-11eb-84bb-de05f7f1ffa0.png">

## Expected

When the port is already in use, then the command exits and warns you about it.

**Comment by spbyrne** [comment]
Oddly when I went to replicate this it would just take over port 300 and the cloud starter would display and work, but if I killed the process the other site I had running at 3000 would start displaying again. Not sure how that's possible.
