### ISSUE TITLE
GSP Building: ReferenceError: localStorage is not defined 

### ISSUE THREAD

**Issue by MightySCollins** [tinacms/tina-cloud-starter#95]
Sorry to waste anyone's time but I have spent all day trying to integrate Tina Cloud and am hitting some issues.

The first thing which really confused me and might want be clarified is when you have not got a query prop on every page an exception gets thrown in the Inner component when useGraphqlForms is called which is slightly obscure.

I also cannot seem to switch to using Tina Cloud. I am getting the error `ReferenceError: localStorage is not defined` and I understand why the token code would use that when a user is editing but I am not sure how to populate the token when next builds.

Also I notice the usage of `createLocalClient` for example at https://github.com/tinacms/tina-cloud-starter/blob/main/pages/posts/%5Bfilename%5D.tsx#L41 and https://github.com/tinacms/tina-cloud-starter/blob/main/pages/index.tsx#L45 which ignores the NEXT_PUBLIC_USE_LOCAL_CLIENT option. Should this not just be `createClient()`?

Sorry if I have misunderstood how this works and thanks for your time.

**Comment by jamespohalloran** [comment]
Hey @MightySCollins, I can speak to part of this!

> Also I notice the usage of createLocalClient for example at https://github.com/tinacms/tina-cloud-starter/blob/main/pages/posts/%5Bfilename%5D.tsx#L41 and https://github.com/tinacms/tina-cloud-starter/blob/main/pages/index.tsx#L45 which ignores the NEXT_PUBLIC_USE_LOCAL_CLIENT option. Should this not just be createClient()?

The reason that the local client is always used within getStaticProps, is so that we can always use local files to statically build your production site.
The Tina Cloud server currently requires a logged-in user session, so it is only used in edit-mode (when your editors are logged in).

**Comment by jamespohalloran** [comment]
Was the `ReferenceError: localStorage is not defined` popping up when using the Tina Cloud Client within `getStaticProps` ? 

I will add that having a long-lived token for accessing the Tina Cloud API (that could be used at build-time) is something we've discussed, but aren't ready for yet.

**Comment by MightySCollins** [comment]
Thanks @jamespohalloran for looking into this. I think I have slightly more understanding now. Your API does not have auth for the server side build so me switching to the `createClient` as opposed to `createLocalClient` causes it to break as it was trying to get a token which uses localStorage on the client side. Instead you run a local server to read the content locally on build.

It might be an idea to check if you are in a browser environment before the call to make it clearer to new people.

**Comment by jamespohalloran** [comment]
> It might be an idea to check if you are in a browser environment before the call to make it clearer to new people.

Yep! that's a great idea. I think this might be a common thing that users may run into when using the client.

**Comment by MightySCollins** [comment]
@jamespohalloran Just had a thought... Does this mean that TinaCMS wont work with GCP if you use `revalidate`? We have pages which pull from another API but when they revalidate hourly the tina graphql server is not running at 4001 as it was only done on the build step.

**Comment by jamespohalloran** [comment]
I haven't used GCP, so let me know if I'm misunderstanding your use case. It sounds like the pages that you're referring to are using SSR, to pull content from another API, and then are cached with GCP? 

Right now, any pages that use Tina Cloud for their content need to be built statically when the local graphql server is still available (at build-time). If the pages being rebuilt with `revalidate` are separate from your pages talking to Tina Cloud, you could mix/match static pages & SSR pages. 

Curious to hear more about your use case though, would the static-only restriction would be a dealbreaker for you?

**Comment by MightySCollins** [comment]
Sorry my phone tried to help. I meant to type `getStaticProps` GSP. Lets say I have a product page which contains some static information from Tina Cloud but I also want to pull the latest product price I would add in `revalidate` so Next.JS will invalidate the props over time. I also might have the list of products are really long, dynamic and constantly changing so I would not want to use `getStaticPaths` but have Next.JS fire the requests when a user requests that product.

We even have use cases on sections like the homepage where we display popular products again with revalidate. Unfortunately Next.JS does not let you mix and match on the same page. Now I could run a local build server firewalled and have the app call that but its quite a bit of overhead and I assume the cli tool is not really optimised for production.
